### ISSUE TITLE
How to list intersections, as they appear in an upset plot

### ISSUE THREAD

**Issue by a14578** [krassowski/complex-upset#164] opened 2022-11-23 23:30 UTC
Hello, 

Is there a way to extract the list of intersections based on the specific order that they appear in, in an upset plot please? 
I've generated an upset plot where the sets are ordered in a specific way but when I use the below command the intersections listed are not in the same order as the upset plot:

upset_data(df, gene_list_ordered)$size

**Comment by krassowski** [comment] 2022-11-23 23:36
Is `$sorted$intersections` what you are looking for?

**Comment by a14578** [comment] 2022-11-23 23:54
I just tried the below but it doesn't seem to work. The last intersection in the upset plot appears in the middle of the extracted list. 

upset_data(df, gene_list_ordered)$size
upset_data(df, gene_list_ordered, sort_sets =FALSE)$size
upset_data(df, gene_list_ordered)$sorted$intersections
upset_data(df, gene_list_ordered, sort_sets = FALSE)$sorted$intersections

**Comment by a14578** [comment] 2022-11-23 23:56
Alternatively is there a way to add intersection labels to the upset plot on the x axis? Perhaps I could extract the list this way

**Comment by krassowski** [comment] 2022-11-24 12:18
> I just tried the below but it doesn't seem to work. The last intersection in the upset plot appears in the middle of the extracted list.
> `upset_data(df, gene_list_ordered)$sorted$intersections`

It should work because this is how the order of intersections is defined:


https://github.com/krassowski/complex-upset/blob/bb3f10a35eb2033754620aacdedc1d52357f13e4/R/upset.R#L984-L987

Please provide a reproducible example so I can look into this.

**Comment by krassowski** [comment] 2022-12-28 21:02
I am going to close this one as I was not able to reproduce the issue, but please reopen if it persists, ideally with a reproducible example. Thanks!

**Closed by krassowski** 2022-12-28 21:02 UTC
Labels: help-request
