### ISSUE TITLE
ComplexUpset can not add barplots on the top since object not found

### ISSUE THREAD

**Issue by yuewangpanda** [krassowski/complex-upset#147] opened 2022-02-18 19:57 UTC
**Objective**

I am trying to make a upset plot with a barplot on its top, like it described here https://krassowski.github.io/complex-upset/articles/Examples_R.html. However, it fails since ggplot object not found. Here is the error:

```{r}
Error in ggplot(mapping = aes(fill = mutation)) + geom_bar(stat = "count",  : 
  object 'mutation' not found
```

**Code**
Here is my demo code:
```{r}
set.seed(123)
data_frame <- data.frame(p1 = sample(x = c("TRUE","FALSE"), size = 20, replace = TRUE),
                         p2 = sample(x = c("TRUE","FALSE"), size = 20, replace = TRUE),
                         p3 = sample(x = c("TRUE","FALSE"), size = 20, replace = TRUE),
                         p4 = sample(x = c("TRUE","FALSE"), size = 20, replace = TRUE),
                         p5 = sample(x = c("TRUE","FALSE"), size = 20, replace = TRUE),
                         mutation = sample(x = c("yes","no"), size = 20, replace = TRUE))

myorder <- c("p1", "p2", "p3", "p4", "p5")

cur_plot <- ComplexUpset::upset(data_frame, 
                                  myorder, 
                                  annotations = list(
                                    'mutation' = (
                                      ggplot(mapping = aes(fill = mutation)) +
                                        geom_bar(stat = "count", position = "fill") +
                                        scale_y_continuous(labels = scales::percent_format()) +
                                        ylab = ("mutation")
                                      )
                                    ),
                                  width_ratio = 0.1, 
                                  height_ratio = 0.8,
                                  set_sizes = (
                                    upset_set_size(geom=geom_bar(width=0.4)) + 
                                      geom_text(aes(label=..count..), 
                                                hjust=1.1, 
                                                stat='count',
                                                size = 3) + 
                                      theme(axis.text.x=element_text(angle=45),
                                            axis.ticks.x=element_line())
                                    ))
```

**Context (required)**

ComplexUpset version: 1.3.3
ggplot2_3.3.5 
R version 4.1.2 (2021-11-01)

Any help would be appreciated.

**Comment by krassowski** [comment] 2022-02-19 01:07
You have a typo: `ylab = ("mutation")` should be `ylab("mutation")`. After this single change the code works for me without issues:

![image](https://user-images.githubusercontent.com/5832902/154779681-0e29b1f3-0f69-41f4-a4a6-7e6e2e4aad69.png)

Sorry about the really unhelpful message, but this is a ggplot issue and not a problem with ComplexUpset.

**Comment by krassowski** [comment] 2022-02-19 01:47
I will close this one as it appears to be caused by a typo, but it you have any further questions or problems please let me know.

**Closed by krassowski** 2022-02-19 01:47 UTC
Labels: help-request
