### ISSUE TITLE
After installing the latest R version 4.1.0 (2021-05-18), ComplexUpset stops w/"Fatal Error" msg!

### ISSUE THREAD

**Issue by sfd99** [krassowski/complex-upset#121] opened 2021-05-20 02:57 UTC
I upgraded today 
to the latest **R version: 4.1.0.**
_Boom!_ 
**ComplexUpset** stopped working now... :-(

Used to work _GREAT_
with the previous versions of R...
(under latest Rstudio and Ubuntu LINUX 20.04).

**ComplexUpset** stops with a:
          "Fatal Error" msg! (shows bomb with fuse),
and then I need to restart Rstudio...

The fatal error message appears 
as soon as I try the basic **upset(movies, ...)** example,
in the **EXAMPLES-R** page:
   https://krassowski.github.io/complex-upset/articles/Examples_R.html

Anybody else 
having this unfortunate **ComplexUpset** problem?.
_Help!._

**SFd99
San Francisco
 - latest R, Rstudio,
 - ComplexUpset V 1.2.1.9000
 - Ubuntu LINUX 20.04**

**Comment by krassowski** [comment] 2021-05-20 15:40
Our checks are passing well [on CRAN](https://cran.r-project.org/web/checks/check_results_ComplexUpset.html) using both the latest release and latest development version, so I do not believe that this is something on our side. Have you tried uninstalling ComplexUpset and installing it again (from CRAN)? And also running the example from command line rather than from RStudio (it is possible that it is RStudio that is at fault here).

**Comment by sfd99** [comment] 2021-05-20 16:36
_**Hi Michal,**_

Yes, 
I UNinstalled & REinstalled ComplexUpset.
Same problem.

(**btw**: 
the UpSetR pkg 
has now the same error mssg!.
Other R pkgs working Ok w/the new R version).

This happened _immediately_ after
upgrading to **R Version 4.1.0  (2021-05-18)**
so it's seems to be due to that?...

Michal,
what is the R version you are testing with?.

**SFd99
San Francisco
   R version 4.1.0 (2021-05-18) ....
latest Rstudio,
ComplexUpset V 1.2.1.9000
Ubuntu LINUX 20.04**

**Comment by sfd99** [comment] 2021-05-21 14:39
Positive UPDATE!!!

Hi Mike,

following your good advice,
I tried tried the simple example:
from Rstudio Terminal, 
(not the usual Rstudio Console).

**It WORKS!** from Terminal:

~$ R
R version 4.1.0 (2021-05-18)
listInput <- list(one = c(1, 2, 3, 5, 7, 8, 11, 12, 13), two = c(1, 2, 4, 5, 10), three = c(1, 5, 6, 7, 8, 9, 10, 12, 13))
library(**UpSetR**)
upset(fromList(listInput), order.by = "freq")

 **UpsetR** chart shows OK in a separate window. _GREAT_!
As you said, 
**Rstudio** might have a problem
with _some_ PKGS, _after upgrading R to V 410_!...

Mike, 
how do I suggest I proceed with Rstudio?. 
Hey! I _always_ follow the advice from Oxford guys :-)

**SFd99
San Francisco
R version 4.1.0 (2021-05-18) .... = latest...
latest Rstudio,
ComplexUpset V 1.2.1.9000
Ubuntu LINUX 20.04**

**Comment by krassowski** [comment] 2021-05-21 15:02
You seem to have an RStudio version (1.4.1103) that does not yet support R 4.1. See: https://community.rstudio.com/t/graphics-error-since-intalling-r-4-1-0/105275. According to linked [PSA](https://community.rstudio.com/t/psa-r-4-1-0-release-requires-rstudio-preview/105209) R 4.1 requires RStudio v1.4.1712-1 Preview and if you use it with the older Rstudio then, quote (emphasis mine):

> You can still use older releases of RStudio with R 4.1, but they don't have support for the new syntax (so you'll see syntax errors), and **you may experience crashes when plotting due to the graphics engine change**.

As a general advice: do not rush with the upgrades of R (or Python for that matter) just when a new major version becomes available, wait ~1 month until the dust settles down.

I will close this issue as it is not a bug in this package but just a problem with RStudio (which is already fixed in newer versions).

**Closed by krassowski** 2021-05-21 15:02 UTC
Labels: potential-bug

**Comment by sfd99** [comment] 2021-05-21 15:09
Thanks for the good advice, Mike!.
Will try to upgrade my Rstudio 
to v1.4.1712-1 Preview.

My Rstudio Menu:
Help / Check for Updates,
returns:
 "You have the latest version"...

Is there a way to get 
that _latest_ Rstudio **Preview** version?.
(maybe it's unstable, too...).

Love ComplexUpset!

**Comment by krassowski** [comment] 2021-05-21 15:32
Sorry no idea, I do not use RStudio. Follow the PSA link to read more.
