### ISSUE TITLE
In upset() plot:  Vertical lines connecting dots are not displayed anymore

### ISSUE THREAD

**Issue by sfd99** [krassowski/complex-upset#23] opened 2020-04-04 19:47 UTC
**_Hi Mike,_**

Today, noticed that 
in  the upset() plot everything is ok,
_but_
the vertical lines "connecting" any dots in a column
are not displayed anymore.

The black dots display fine,
but without "connector" lines btw them.

Ex: 
Simple Upset Plot
 **(or with any other +complex example),**
_no_  vertical "connector" lines are shown  btw dots.

upset(
    movies, genres,
    base_annotations=list('Intersection size'=intersection_size(counts=FALSE)),
    min_size=100,
    width_ratio=0.3
)

**ComplexUpset pkg v 052,** 
**w/ Ubuntu Linux 18.04, latest Rstudio and R.**
see image below:
 
![image](https://user-images.githubusercontent.com/3316239/78460042-ead02100-7693-11ea-9ff0-87c14b9f010d.png)

**Comment by krassowski** [comment] 2020-04-04 20:16
Thank you for letting me know. I will look into this soon. In the meantime, please have a try with the latest version 0.5.6 (the examples in the documentation were generated with it and do show the connectors).

**Comment by sfd99** [comment] 2020-04-04 20:28
Tried w/ version 056,
but same result
...no connecting lines btw dots., (as shown in image above).

Funny, I seem to recall 
that those vertical connecting lines
were shown normally yesterday! (w/ the older ver 052...).

**Comment by krassowski** [comment] 2020-04-04 20:36
Did you update any packages? Could you provide `sessionInfo()` result, please?

**Comment by sfd99** [comment] 2020-04-04 20:44
I restarted Rstudio without any other packages.
Upset Plot **does** show the connecting lines OK!.

Then I sourced / loaded my usual R pkgs.
Result: 
the plot is OK but NO connecting lines.

Here's
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8      
 [2] LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                 
 [9] LC_ADDRESS=C              
[10] LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8
[12] LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices
[4] utils     datasets  methods  
[7] base     

other attached packages:
[1] ComplexUpset_0.5.6 janitor_1.2.1     
[3] magrittr_1.5       reshape2_1.4.3    
[5] tidyr_1.0.2        ggplot2_3.3.0     
[7] dplyr_0.8.5       

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4         
 [2] pillar_1.4.3       
 [3] compiler_3.6.3     
 [4] plyr_1.8.6         
 [5] tools_3.6.3        
 [6] digest_0.6.25      
 [7] lifecycle_0.2.0    
 [8] tibble_3.0.0       
 [9] gtable_0.3.0       
[10] pkgconfig_2.0.3    
[11] rlang_0.4.5        
[12] cli_2.0.2          
[13] rstudioapi_0.11    
[14] patchwork_1.0.0    
[15] withr_2.1.2        
[16] stringr_1.4.0      
[17] vctrs_0.2.4        
[18] ggplot2movies_0.0.1
[19] grid_3.6.3         
[20] tidyselect_1.0.0   
[21] glue_1.4.0         
[22] R6_2.4.1           
[23] fansi_0.4.1        
[24] farver_2.0.3       
[25] purrr_0.3.3        
[26] scales_1.1.0       
[27] ellipsis_0.3.0     
[28] assertthat_0.2.1   
[29] colorspace_1.4-1   
[30] labeling_0.3       
[31] stringi_1.4.6      
[32] munsell_0.5.0      
[33] crayon_1.3.4       
>

**Comment by sfd99** [comment] 2020-04-04 20:54
In case it helps,
_below_ is the myLibs.R file I "source" every time 
I start an Rstudio session.

It must be one of these pkgs interfering
with the display of connector lines...

library(dplyr)
library(ggplot2)
library(tidyr)
library(reshape2)
library(magrittr)
library(janitor) # crosstab: mtcars %$% table(cyl, gear)
library(janitor)
# tabyl(mtcars, cyl)
# tabyl(mtcars, cyl, gear)
# tabyl(mtcars, cyl, gear, am)
## visdat::vis_dat()
# will always show AL columns, regardless of the width of the tibble...
options(tibble.width = Inf) 
# never import char strings as Factor, always keep as "CHAR"!
options(stringsAsFactors=F) 

########### END ############

**Comment by krassowski** [comment] 2020-04-04 20:56
Thank you for providing these details. `options(stringsAsFactors=F)` is likely the cause. I will fix this in the next version.

**Comment by sfd99** [comment] 2020-04-04 20:58
Great!. 
Will monitor this thread,
update to next version 
and report back to you!... :-)

**Comment by krassowski** [comment] 2020-04-04 21:21
It should be fixed now - please have a try with 0.5.7 and let me knkow if the update helped!

**Comment by sfd99** [comment] 2020-04-04 21:34
Perfect, Mike!.
Connecting lines all there, again!.
Thanks!...

I'm sure many other R users
would have sourced:
 options(stringsAsFactors=F) 

So, a stitch in time saves nine. Ah!. :-)
----
btw: (if I may...)
any chance to add total Counts
to the horizontal bars 
in the **Set Size** sub-plot?.
(Similar to the Count numbers
in the plot _vertical_ bars...).

Could be very useful 
to show those **Set Size** counts...

**Comment by krassowski** [comment] 2020-04-04 22:20
Great to hear that it worked :tada:! I will close this issue for now, but please do open a new one if you encounter any other problems or would like to suggest a new feature.

I went ahead and opened an issue for the set size counts (#24) - please see over there for an example for how it could be accomplished.

**Closed by krassowski** 2020-04-04 22:20 UTC

**Comment by sfd99** [comment] 2020-04-04 22:39
SUPER!.
Will take a look.

Have a safe evening, Mike!.
